### ISSUE TITLE
Re-write the UI to use Vue.js

### ISSUE THREAD

**Issue by FreezePhoenix** [NexusNull/bot-web-interface#1]
I'd like to request that the UI be re-written to use Vue.js
Vue.js has several things to offer:
 - Better performance due to HTML elements not being recreated
 - Allow animation
 - Make implementation of an Inventory Query easier.

If you need some help with Vue.js, some things you may want to look at:
 - https://github.com/FreezePhoenix/Angels-And-Demons
 - https://vuejs.org/

**Comment by NexusNull** [comment]
This is not an ALBot issue so moved to Bot-web-interface.
I'll review the library and decide wheter to implement it at a later time.
